# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DroneFarmPro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 848)
        MainWindow.setStyleSheet("background-color: rgb(104, 109, 118);\n"
                                 "border-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1101, 81))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-top-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 10, 536, 59))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Bold")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel{\n"
                                 "        color: white;\n"
                                 "\n"
                                 "    }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(850, 10, 91, 51))
        self.label_8.setStyleSheet("image: url(:/smartFarming/control-center.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 1101, 671))
        self.frame_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 110, 531, 421))
        self.frame_3.setStyleSheet("border-color: rgb(85, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_plot1 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_plot1.setGeometry(QtCore.QRect(20, 30, 461, 151))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plot1.setFont(font)
        self.pushButton_plot1.setStyleSheet("QPushButton{\n"
                                            "    background-color: rgb(7, 25, 82);\n"
                                            "        border: 1px solid;\n"
                                            "        border-radius: 15px;\n"
                                            "        color: white;\n"
                                            "    }\n"
                                            "QPushButton:pressed{\n"
                                            "        background-color: skyblue\n"
                                            "    }")
        self.pushButton_plot1.setObjectName("pushButton_plot1")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 91, 81))
        self.label_4.setStyleSheet("image: url(:/smartFarming/field.png);\n"
                                   "background-color: rgb(7, 25, 82);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_plot1_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_plot1_2.setGeometry(QtCore.QRect(20, 210, 461, 151))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plot1_2.setFont(font)
        self.pushButton_plot1_2.setStyleSheet("QPushButton{\n"
                                              "    background-color: rgb(7, 25, 82);\n"
                                              "        border: 1px solid;\n"
                                              "        border-radius: 15px;\n"
                                              "        color: white;\n"
                                              "    }\n"
                                              "QPushButton:pressed{\n"
                                              "        background-color: skyblue\n"
                                              "    }")
        self.pushButton_plot1_2.setObjectName("pushButton_plot1_2")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(70, 240, 91, 81))
        self.label_9.setStyleSheet("image: url(:/smartFarming/field.png);\n"
                                   "background-color: rgb(7, 25, 82);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(560, 110, 531, 421))
        self.frame_4.setStyleSheet("border-color: rgb(85, 255, 255);\n"
                                   "border-top-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_plot1_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_plot1_3.setGeometry(QtCore.QRect(30, 210, 461, 151))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plot1_3.setFont(font)
        self.pushButton_plot1_3.setStyleSheet("QPushButton{\n"
                                              "    background-color: rgb(7, 25, 82);\n"
                                              "        border: 1px solid;\n"
                                              "        border-radius: 15px;\n"
                                              "        color: white;\n"
                                              "    }\n"
                                              "QPushButton:pressed{\n"
                                              "        background-color: skyblue\n"
                                              "    }")
        self.pushButton_plot1_3.setObjectName("pushButton_plot1_3")
        self.pushButton_plot1_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_plot1_4.setGeometry(QtCore.QRect(30, 30, 461, 151))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plot1_4.setFont(font)
        self.pushButton_plot1_4.setStyleSheet("QPushButton{\n"
                                              "    background-color: rgb(7, 25, 82);\n"
                                              "        border: 1px solid;\n"
                                              "        border-radius: 15px;\n"
                                              "        color: white;\n"
                                              "    }\n"
                                              "QPushButton:pressed{\n"
                                              "        background-color: skyblue\n"
                                              "    }")
        self.pushButton_plot1_4.setObjectName("pushButton_plot1_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(70, 240, 91, 81))
        self.label_10.setStyleSheet("image: url(:/smartFarming/field.png);\n"
                                    "background-color: rgb(7, 25, 82);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(80, 60, 91, 81))
        self.label_11.setStyleSheet("image: url(:/smartFarming/field.png);\n"
                                    "background-color: rgb(7, 25, 82);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.widget.setObjectName("widget")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 531, 81))
        self.frame_5.setStyleSheet("background-color: rgb(234, 238, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
                                   "        color: black;\n"
                                   "\n"
                                   "    }\n"
                                   "\n"
                                   "image: url(:/blueIcons/blueIcons/target.svg);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 81, 61))
        self.label_3.setStyleSheet("image: url(:/smartFarming/crop_monitoring.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(560, 10, 531, 80))
        self.frame_6.setStyleSheet("background-color: rgb(234, 238, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(160, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR Medium")
        font.setPointSize(18)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 111, 61))
        self.label_6.setStyleSheet("image: url(:/smartFarming/drone.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(130, 550, 961, 111))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 251, 244);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 550, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IntelOne Display AR")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(960, 780, 141, 21))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FieldDrone Command Suite"))
        self.pushButton_plot1.setText(_translate("MainWindow", "Plot 1"))
        self.pushButton_plot1_2.setText(_translate("MainWindow", "Plot 2"))
        self.pushButton_plot1_3.setText(_translate("MainWindow", "Plot 2"))
        self.pushButton_plot1_4.setText(_translate("MainWindow", "Plot 1"))
        self.label_2.setText(_translate("MainWindow", "Crop Monitoring"))
        self.label_5.setText(_translate("MainWindow", "Weed Treatment"))
        self.label_7.setText(_translate("MainWindow", "Status:"))
        self.label_12.setText(_translate("MainWindow", "Developed by SRINPEK"))


import resources_rc
